# Generated by Django 3.2.13 on 2022-07-07 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gbapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dev',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('img', models.ImageField(upload_to='image')),
                ('desc', models.TextField()),
            ],
        ),
    ]
